# images

title: Bild

accept:
  mime: image/*

options:
  changeName: true
  delete: true
  replace: true
  update: true

fields:

  sort:
    type: hidden

  description:
    extends: fields/description
    label: Caption

  credits:
    label: Credits
    type: text
    before: ©

  exclude:
    type: toggle
    label: Hide from gallery
    text:
      - Show in gallery
      - Hide from gallery

  videoUrl:
    type: url
    placeholder: https://
    label: Video Url
    help: If this image is actually a placeholder for a video. YouTube or Vimeo only!
    icon: video
