title: Page

icon: page

status:
  draft:
    label: Draft
    text: The page is still in draft mode. It can only be seen by logged in editors.
  unlisted:
    label: Visible
    text: The page is visible.

options:
  changeSlug:	true
  changeStatus:	true
  changeTemplate:	false
  changeTitle: true
  delete:	true
  preview: true
  read:	true
  update: true

fields:

  body: fields/posts/content
