title: Default Post

# sorting by date
num: '{{ page.date.toDate("Ymd") }}'

icon: 🏓

options:
  changeSlug:	true
  changeStatus:	true
  changeTemplate:	true
  changeTitle:	true
  delete:	true
  preview: true
  read:	true
  update: true

tabs:

  tab_info: tabs/posts/both

  tab_workflow: tabs/workflow
