title: Default Post

# sorting by date
num: '{{ page.date.toDate("Ymd") }}'

icon: 🏓

options:
  changeSlug:	true
  changeStatus:	true
  changeTemplate:	true
  changeTitle:	true
  delete:	true
  preview: true
  read:	true
  update: true

columns:
  - width: 2/3
    sections:
      fields1:
        type: fields
        fields:

          subtitle: fields/posts/subtitle

      uploads:
        extends: sections/uploads
        layout: cards
        headline: Gallery

      fields2:
        type: fields
        fields:

          body: fields/posts/content

          link:
            extends: fields/url
            label: External Link
            width: 2/3

          linkRedirect:
            type: toggle
            label: Open Link Instantly
            width: 1/3
            icon: open

  - width: 1/3
    sections:

      fields3:
        type: fields
        fields:

          date:
            extends: fields/date
            required: true

          semester: fields/posts/semester

          channels: fields/posts/channels

          type: fields/posts/type

          location: fields/posts/location

          persons: fields/posts/persons

          categories: fields/posts/categories

          keywords:
            extends: fields/keywords
            required: true
            min: 2
