title: Site

tabs:

  content:
    label: Content
    icon: home

    columns:

      - width: 1/2
        sections:

          # list of latest posts
          posts:
            headline: Content
            extends: sections/pages
            template: posts
            create: false
            info: "{{ page.children.count }} Posts"

          drafts:
            extends: sections/posts
            headline: Posts in the making
            status: draft
            parent: site.find('posts')
            template: post

      - width: 1/2
        sections:

          # list all domains
          channels:
            headline: Channels
            extends: sections/pages
            template: channel

  info:
    extends: tabs/info
    columns:
      main:
        fields:

          imprint:
            extends: fields/url
            label: Imprint Link
