title: Site

tabs:

  content:
    label: Content

    columns:

      - width: 1/2
        sections:

          # list all domains
          channels:
            headline: Channels
            extends: sections/pages
            template: channel

      - width: 1/2
        sections:

          # list of latest posts
          posts:
            headline: Content
            extends: sections/pages
            template: posts

  info:
    extends: tabs/info
    columns:
      main:
        fields:

          imprint:
            extends: fields/url
            label: Imprint Link
