title: Site

tabs:

  content:
    label: Content

    columns:

      - width: 1/2
        sections:

          # list all domains
          channels:
            headline: Channels
            extends: sections/pages
            template: channel

      - width: 1/2
        sections:

          # list of latest posts
          posts:
            headline: Content
            extends: sections/pages
            template: posts

  info:
    label: Info

    columns:

      - width: 2/3
        fields:

          image: fields/image

          description: fields/description

          links: fields/links

          keywords: fields/keywords

          imprint:
            type: url
            label: Imprint Link

      - width: 1/3
        sections:

          uploads:
            extends: sections/uploads
